### ISSUE TITLE
Crash upon attempting to look up the recipe for water in JEI

### ISSUE THREAD

**Issue by 00-Steven** [BrassGoggledCoders/Workshop#9]
Crash log:
https://pastebin.com/7uSV7jJt

Game crashes when I use JEI to look up the recipe for water.

**Comment by FreneticScribbler** [comment]
Looks like a Titanium issue?

**Comment by SkySom** [comment]
It is. One of Lanse's PRs changed code so it shows up as missing for dependent mods.

**Comment by SkySom** [comment]
Should be fixed in the custom build y'all have, but I'll finish up the PR.
